#!/usr/bin/env bash
# Script that transfers a file from our client to a server.

if (($# < 4))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    FILE=$1
    IP=$2
    USER=$3
    SSH_KEY=$4
    sudo scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USER"@"$IP":~/
fi
