#!/usr/bin/env bash
# Install nginx server

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
sed -i "s/listen 80;\n/listen 80;\nrewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart


