#!/usr/bin/env bash
# Install nginx server

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sudo sed -i "s/listen 80 default_server;/listen 80 default_server;\n\tlocation \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart


