#!/usr/bin/env bash
# Install nginx server

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i "s/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\terror_page 404 \/error404.html;\n\n/" /etc/nginx/sites-available/default
sudo service nginx restart
