#!/usr/bin/env bash
# Install nginx server

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error404.html
host_name=$(hostname)
old_config="server_name _;"

# add redirection in the path /redirect_me
new_config="${old_config}\n\n\
        location \/redirect_me {\n\
            return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\
        }\n"

# add 404 error page
new_config="${new_config}\n\
        error_page 404 \/error404.html;\n"

# add header to server response
new_config="${new_config}\n\
        add_header X-Served-By ${host_name} always;\n"

sed -i "s/$old_config/$new_config/" /etc/nginx/sites-available/default
sudo service nginx restart
