#!/usr/bin/env bash
# Install and configure HAProxy

apt-get update
apt-get install -y haproxy=1.6.\*

config='backend myBackend
    mode http
    balance roundrobin
    server web-01 34.138.86.55:80
    server web-02 34.75.178.179:80

frontend myFrontend
        bind :80
        default_backend myBackend'

echo "$config" >> /etc/haproxy/haproxy.cfg

systemctl restart haproxy
