#!/usr/bin/env bash
# create a compressed backup for the all databases in localhost

TAR_FILE_NAME=$(date '+%d-%m-%Y')
mysqldump -u root --password="$1" --all-databases > backup.sql
tar -czvf "${TAR_FILE_NAME}.tar.gz" backup.sql
