#!/usr/bin/env bash
# kills the process 7-highlander..
on_SIGINT () {
echo "Y U no love me?!"
  exit
}
on_SIGTERM () {
    echo "I hate the kill command"
    rm /var/run/holbertonscript.pid
    exit
}
on_SIGQUIT () {
    rm /var/run/holbertonscript.pid
    exit
}

echo $$ > /var/run/holbertonscript.pid
trap on_SIGTERM SIGTERM
trap on_SIGQUIT SIGQUIT
trap on_SIGINT SIGINT

while (( 1 ))
do
    echo To infinity and beyond
    sleep 2
done
