#!/usr/bin/env bash
# daemond thath write I am alive! in /tmp/my_process file each 2 seconds
program_name="manage_my_process"
action_request="$1"

case $action_request in
        "start")
            bash "$program_name" &
            pgrep -fn $program_name > /var/run/my_process.pid
            echo manage_my_process started
            ;;
        "stop")
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
            echo manage_my_process stopped
            ;;
        "restart")

            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid

            bash "$program_name" &
            pgrep -fn $program_name > /var/run/my_process.pid
            echo manage_my_process restarted
            ;;
        *)
            echo "Usage: manage_my_process {start|stop|restart}"
            ;;
    esac

