#!/usr/bin/env bash
#Displays formatted contento af a file /etc/passwd
file_name="/etc/passwd"
while IFS= read -r line
do
  USERNAME=$(echo "$line" | cut -d ":" -f 1)
  GROUP_ID=$(echo "$line" | cut -d ":" -f 4)
  HOME_DIRECTORY=$(echo "$line" | cut -d ":" -f 6)
  COMMAND=$(echo "$line" | cut -d ":" -f 7)
  USER_ID=$(echo "$line" | cut -d ":" -f 3)
  PASSWORD=$(echo "$line" | cut -d ":" -f 2)
  INFO=$(echo "$line" | cut -d ":" -f 5)
  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $INFO"
done < "$file_name"
