#!/usr/bin/env bash
#Displays Holberton School 10 times using while loop and show 'bad luck' at 4 and 'good luck' at 8.
i=0
while ((i++ < 10))
do
    if [ $i -eq 4 ]
    then
        echo 'bad luck'
    elif [ $i -eq 8 ]
    then
        echo 'good luck'
    else
        echo 'Holberton School'
    fi
done
