#!/usr/bin/env bash
# execute nginx as nginx user
pkill apache2
chmod a+r /etc/nginx/nginx.conf
sed -i "s/listen 80 d/listen 8080 d/" /etc/nginx/sites-available/default
sudo -u nginx /etc/init.d/nginx start
